"""create lecturehall table

Revision ID: a39f31afe4a5
Revises: 
Create Date: 2023-12-18 19:51:19.679842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39f31afe4a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturehalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.Text(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturehalls')
    # ### end Alembic commands ###
